name = "alvas-api"
compatibility_date = "2024-04-25"
main = "src/main.ts"

# --- ENTORNOS Y VARIABLES GLOBALES ---
[vars]
AUTH_TOKEN_TTL_SEGUNDOS = "900"
REFRESH_TOKEN_TTL_SEGUNDOS = "604800"

# --- ENTORNO POR DEFECTO (Development / Local) ---
[[d1_databases]]
binding = "DB"
database_name = "alvas-dev"
database_id = "3e42be52-b6b0-4519-a090-4aea158cd2b6"
migrations_dir = "drizzle"

# --- ENTORNO STAGING ---

[env.staging]
name = "alvas-api-staging"
[env.staging.vars]
AUTH_TOKEN_TTL_SEGUNDOS = "900"
REFRESH_TOKEN_TTL_SEGUNDOS = "604800"

[[env.staging.d1_databases]]
binding = "DB"
database_name = "alvas-staging"
database_id = "749211d9-70f1-429d-a08c-592af8ed5ef4"
migrations_dir = "drizzle"

# --- ENTORNO PRODUCCIÓN ---
[env.production]
name = "alvas-api"
[env.production.vars]
AUTH_TOKEN_TTL_SEGUNDOS = "900"
REFRESH_TOKEN_TTL_SEGUNDOS = "604800"

[[env.production.d1_databases]]
binding = "DB"
database_name = "alvas-main"
database_id = "5a204ddb-0dc0-41da-9cfc-38e985debe67"
migrations_dir = "drizzle"
